### ISSUE TITLE
difference between filter and takeWhile

### ISSUE THREAD

**Issue by ryoppippi** [ugaya40/leseq#5]
Is there any difference between filter and takeWhile?
They both seem to work almost identically, so if there is any difference, we would be grateful to hear about it!

**Comment by ugaya40** [comment]
@ryoppippi 
Hello, thank you for the issue.
Please see the difference between **filter** and **takeWhile** below:

https://codesandbox.io/s/difference-between-filter-and-takewhile-3lh7p9?file=/src/index.ts

As shown above, unlike **filter**, **takeWhile** stops enumerating as soon as an item that doesn't meet the condition is found.

**Comment by ryoppippi** [comment]
@ugaya40 
I got it ! Thanks!!
